print("Hi from init")
require "rameez.options"
require "rameez.keymaps"
require "rameez.plugins"
require "rameez.cmp"
require "rameez.lsp"
require "rameez.telescope"
require "rameez.treesitter"
require "rameez.autopairs"
require "rameez.comment"
require "rameez.gitsigns"
require "rameez.nvim-tree"
require "rameez.bufferline"
require "rameez.toggleterm"
